name=MHZ19_Universal
version=1.0.0
author=Artek97
maintainer=Artek97
sentence=A universal library for the MH-Z19B/C/D CO2 sensor for Arduino AVR, ESP32, and STM32 platforms.
paragraph=This library supports reading CO2 concentration via UART or PWM.
category=Sensors
url=https://github.com/fikrielektro21
architectures=*

